### ISSUE TITLE
Allow toggling the rgb on the base core when pressing any key

### ISSUE THREAD

**Issue by colhay** [TsFreddie/much-programming-core#1]
I am going to look into the code and see if it is possible to toggle the rgb light during a key press. This is a feature I want because I am using fn and fn1 to essentially access layers, however they are only activated when the key is being pressed. I plan to toggle the rgb to red only when the fn1 key is pressed and similarly toggle it to blue only when the fn key is pressed. This offers no functional value, but I would enjoy having it as a feature.

If I find this is not possible, I intend to add functionality for triggering a macro when a key is released. This would allow me to press a key to access a layer, and set up a macro to automatically return to L0 when that key is released. This would make use of the rgb led by default.

**Comment by TsFreddie** [comment]
Sorry, I couldn't find any keycode that may associate with RGB control. I'm afraid there are nothing we can do about this with a frontend mod.
