### ISSUE TITLE
Use the 3 leds

### ISSUE THREAD

**Issue by Sasha-Kachanov** [TsFreddie/much-programming-core#13]
I have a regular non rgb vortex core. It has the caps light, the layer light, and the right spacebar light that turns on if you have the HWP firmware and use the on-board programming functionality.

I believe you've exposed all the codes that we could assign in that erlenmeyer flask icon and none of them have to do with triggering the lights.

From what I can't tell we can't have any fun with the leds at all. I thought it might be fun to have the 2 rgb/spacebar LEDs have a little party by cycling through the 3 available colors. Can you confirm that we can't control LED behaviour at all?

**Comment by TsFreddie** [comment]
At least I can't find anything customizable that would trigger LED changes.

**Comment by Sasha-Kachanov** [comment]
I wonder if there's yet a third firmware that's even better than the stock 2 that allows for LED control! :) Thanks for your work, your tool is great.
Closing the issue
