### ISSUE TITLE
Shift + Fn1 vs Fn1 + Shift

### ISSUE THREAD

**Issue by larsks** [TsFreddie/much-programming-core#15]
I've noticed that the order in which I press modifier keys has an impact on what characters keys will produce.

If I hold down `Fn1` and press `A`, I get the the character `2`. If I continue to hold down the `Fn1` key but then also press the `shift` key, typing `A` will continue to produce `2`. This was unexpected.

On the other hand, if I first press the shift key, typing `A` produces `A`. If I continue to hold down the `shift` key and also press `Fn1`, pressing `A` will generate `@`.  If I release the `shift` key I will start to get `2`.

Is this expected? A hardware problem? A firmware problem?

Thanks!

**Comment by TsFreddie** [comment]
it is expected. When you have Fn1 held. Your shift will only trigger the function bind to the Fn1 layer on your shift key.

Try this:
![image](https://user-images.githubusercontent.com/3797859/94220682-73ac7480-fee1-11ea-9e5b-aca12d271728.png)

**Comment by TsFreddie** [comment]
And of course, you are most likely need to do this for other layers and other modifier keys as well.

**Comment by larsks** [comment]
Thanks so much! I saw that note in the docs ("You might find it handy on modifier keys, when you need shift to act like shift in all layers.") but I didn't really understand what it was saying. I guess there's nothing like a practical problem to illuminate something :),
