### ISSUE TITLE
Change the location of Fn key

### ISSUE THREAD

**Issue by lph86** [TsFreddie/much-programming-core#16]
Hi @TsFreddie,

Here's my current layout: 
<img width="932" alt="Screen Shot 2020-10-08 at 14 48 12" src="https://user-images.githubusercontent.com/2590490/95434240-36cd8c80-097b-11eb-9c7c-c36b110a604d.png">
I changed the Fn, Pn location, removed Fn1. And it's working ok now.
So why don't you allow to change Fn location in your tool?

**Comment by TsFreddie** [comment]
can you provide more detail of how you changed fn's position with MPC firmware?

I've tested various solutions and the RWin key always act as fn no matter how I map the ktm code.

**Comment by TsFreddie** [comment]
also your layout can be done without changing fn's position. you just swap fn and pn layer.

**Comment by lph86** [comment]
Yes, I can swap, but I don't want to do any extra steps after flashing binary.
I export layout as json, then replace Fn <=> Pn in that json file (offline step). 
After that I re-import it to generate binary file.

The Fn,Pn,Fn1 position on my stock firmware seems different with your default layout.
My keyboard doesn't have Menu key.
![2020-10-08 17 05 05](https://user-images.githubusercontent.com/2590490/95445173-e9f0b280-0988-11eb-8f68-e329256aa1cf.jpg)

**Comment by TsFreddie** [comment]
is that a rgb version, i don't have a RGB core on hand, might be different. could you sent me the binary and json file so I can check. i'm pretty sure the way you did it won't work on my keyboard

**Comment by TsFreddie** [comment]
also please confirm that you can type F1-F12 and switch profile as well.

**Comment by lph86** [comment]
Yes, I have rbg version, F1-F12, switch profile all working well.
[new2fn.cys.txt](https://github.com/TsFreddie/much-programming-core/files/5352259/new2fn.cys.txt)
[new2fn.json.txt](https://github.com/TsFreddie/much-programming-core/files/5352260/new2fn.json.txt)

**Comment by TsFreddie** [comment]
Quick update. Looks like the "Fn" key can only be a modifier key (Fn\Fn1\Pn), then it'll work. You can't change it to something else. I'll update the UI to reflect this behaviour.

**Comment by ghost** [comment]
Can I ask for clarification on this issue, is there a way to reassign the Fn key currently using your tool?

Furthermore, would I be able to assign 'Alt' to the key position that is currently 'Fn'?

Thanks for making this tool, it's really useful!
