### ISSUE TITLE
Singe character map

### ISSUE THREAD

**Issue by axeldetlofsson** [TsFreddie/much-programming-core#18]
Hi, 
Thanks for this great software, makes my day much esier, just one question/feature request:
Is it possible to map ex. { to a key, without creating a macro with time delay?

Thanks!

**Comment by TsFreddie** [comment]
No. The mpc firmware doesn't have the ability to send text and there is no physical keycode for '{'.

**Comment by axeldetlofsson** [comment]
Oh okey, thanks for the fast answere!

**Comment by axeldetlofsson** [comment]
Have you experimented with installing any other firmware like QMK?

**Comment by TsFreddie** [comment]
You need hardware debugging tools to unlock chip. see: https://github.com/pok3r-custom/pok3r_re_firmware/wiki/HT32-Unlocking

I personally never done it tho. You can ask the guy porting the firmware, I've seen him helping people in his repo's issue thread.

**Comment by axeldetlofsson** [comment]
Thanks alot man!
