### ISSUE TITLE
Shift and Fn1 behavior

### ISSUE THREAD

**Issue by Lawiak** [TsFreddie/much-programming-core#19]
Hi,
first of all, great work, your editor makes it so much easier to change the layout! I finally have a reason to use the MPC firmware on my Core.
But one thing I did notice:
Shift in combination with Fn1 seems to be a bit strange, it appears that the order in which I press the keys seems to matter. If for example I want to type a ! I have to press \<Shift\>, then \<Fn1\>, then \<Tab\>.
If I press \<Fn1\>, then \<Shift\>, then \<Tab\> I get „1“, not „!“.
With the normal non-MPC-firmware the order doesn‘t matter.
Any way to fix this?

Thanks
Lawiak

**Comment by TsFreddie** [comment]
see #15

**Comment by Lawiak** [comment]
Yes, that was it! Sorry for not seeing it before I opened this issue. 
And when I think about it it really does make sense, so it wasn‘t really an issue in the first place!
