### ISSUE TITLE
Can i have full RGB effects from Core by MPC

### ISSUE THREAD

**Issue by piemap04** [TsFreddie/much-programming-core#20]
Hello sir, i really love your program. It helps me a lot when I used my Core RGB.
But when i used it, my Core has lost some RGB effect, i have to flashed Core by HWP if i want it back.
I really like this keyboard but the stock layout so.... Now i can fix it but my RGB can't work like it used to.
So can you update your progame to fix it, please.
I would be very grateful if you could do that. Thanks a lot.

**Comment by TsFreddie** [comment]
MPC firmware is not design for RGB Core. You can try using Pn + Q through U for RGB control if that is even available in MPC.

The MPC firmware is made by Vortex and this tool is only a configuration tool for the official firmware. I cannot add features that weren't available in the firmware.
