### ISSUE TITLE
FN1 Functionality MPC / HWP

### ISSUE THREAD

**Issue by remiteeple** [TsFreddie/much-programming-core#21]
There is an issue with the base MPC firmware that I thought you may be able to solve.

When using the HWP firmware the FN1 key can be pressed before SHIFT to input SHIFT + FN1 keys, when using even the base MPC firmware to input any symbols or SHIFT + FN1 shift MUST be pressed before the FN1 key as any other modifier input is seemingly ignored when FN1 is held.

No idea if there is a possible fix via this tool, figured I'd bring it to your attention.

**Comment by TsFreddie** [comment]
see #15 and #19

**Comment by remiteeple** [comment]
Amazingly quick response!  Sorry about that, I forgot to look at the closed issues.
