### ISSUE TITLE
Add FN1, FN and PN to Macros

### ISSUE THREAD

**Issue by justalittle-BIT** [TsFreddie/much-programming-core#23]
Would it be possible to add the Core function keys in the Macros?
e.g. I would like to use the combination of Fn+Fn1 as toggle for Fn1.

Thanks!

**Comment by TsFreddie** [comment]
If you want a toggle, profile switch is probably better for that and natively supported by the keyboard.

![image](https://user-images.githubusercontent.com/3797859/112712874-1e433580-8f0d-11eb-904b-951d5b0bb2e3.png)

Then do whatever you do with Fn1 on the base layer in L1

**Comment by justalittle-BIT** [comment]
Thanks for the reply.
Unfortunately I'm not able to put any Fn Layer command on the Fn1.
Is it to be considered a bug or a feature? 😄

**Comment by TsFreddie** [comment]
> Thanks for the reply.
> Unfortunately I'm not able to put any Fn Layer command on the Fn1.
> Is it to be considered a bug or a feature? 😄

I guess the firmware just ignores non base layers on modifiers. I used to have them disabled when the base key is a modifier, but some people swore they work but they never worked for me, so i just removed the restriction.

**Comment by TsFreddie** [comment]
> Is it to be considered a bug or a feature? 😄

I don't know since I didn't make the firmware. I can't say for sure how Vortex designed the firmware exactly. But if it doesn't work, maybe you should look into some software solutions like autohotkey or karabiner.
