### ISSUE TITLE
MPC Firmware no longer downloadable/ supported by Vortexgear

### ISSUE THREAD

**Issue by KreeseXD** [TsFreddie/much-programming-core#28]
The tool's UI references to a link to download the MPC firmware from Vortex's own website; however it looks like they dropped references to their own UI tool that this is based on.

Right clicking the link and trying to force to save the file does not work. However, mechanicalkeyboards.com still has a firmware file uploaded. Not sure what the right way to go about this, but as of filing this issue, the MPC firmware is no longer available

**Comment by TsFreddie** [comment]
I guess I'll just upload them to this repo. Vortex is not going to update the firmware anyway.
