### ISSUE TITLE
Macro limit?

### ISSUE THREAD

**Issue by isti115** [TsFreddie/much-programming-core#7]
There seems to be a 20 macro limit.
Do you know what could be the cause of this or any idea how to fix it?
If I map more than 20 keys to macros, the rest just stop working.

**Comment by isti115** [comment]
(This has already been discovered before by a reddit user: https://www.reddit.com/r/MechanicalKeyboards/comments/9hq70z/vortex_core_users_i_present_you_with_a_better/ebi8fuw)

**Comment by TsFreddie** [comment]
It's a firmware limitation. I am not exactly sure whether it is intentional or not. There is nothing I can do.

**Comment by isti115** [comment]
Thanks for the explanation (And all your work as well, you made my keyboard _MUCH_ more useful!), we will have to live with this limitation then.
